//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardDataGatherer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryCostMetric
    {
        public long ID { get; set; }
        public string InventoryType { get; set; }
        public string Warehouse { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
