//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardDataGatherer
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemprice
    {
        public string item { get; set; }
        public System.DateTime effect_date { get; set; }
        public string curr_code { get; set; }
        public Nullable<decimal> unit_price1 { get; set; }
        public Nullable<decimal> unit_price2 { get; set; }
        public Nullable<decimal> unit_price3 { get; set; }
        public Nullable<decimal> unit_price4 { get; set; }
        public Nullable<decimal> unit_price5 { get; set; }
        public Nullable<decimal> unit_price6 { get; set; }
        public Nullable<byte> reprice { get; set; }
        public Nullable<decimal> brk_qty__1 { get; set; }
        public Nullable<decimal> brk_qty__2 { get; set; }
        public Nullable<decimal> brk_qty__3 { get; set; }
        public Nullable<decimal> brk_qty__4 { get; set; }
        public Nullable<decimal> brk_qty__5 { get; set; }
        public Nullable<decimal> brk_price__1 { get; set; }
        public Nullable<decimal> brk_price__2 { get; set; }
        public Nullable<decimal> brk_price__3 { get; set; }
        public Nullable<decimal> brk_price__4 { get; set; }
        public Nullable<decimal> brk_price__5 { get; set; }
        public string base_code__1 { get; set; }
        public string base_code__2 { get; set; }
        public string base_code__3 { get; set; }
        public string base_code__4 { get; set; }
        public string base_code__5 { get; set; }
        public string dol_percent__1 { get; set; }
        public string dol_percent__2 { get; set; }
        public string dol_percent__3 { get; set; }
        public string dol_percent__4 { get; set; }
        public string dol_percent__5 { get; set; }
        public string pricecode { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public string uf_pref_type { get; set; }
    }
}
