//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardDataGatherer
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public string type { get; set; }
        public string job1 { get; set; }
        public short suffix { get; set; }
        public Nullable<System.DateTime> job_date { get; set; }
        public string cust_num { get; set; }
        public string ord_type { get; set; }
        public string ord_num { get; set; }
        public Nullable<short> ord_line { get; set; }
        public Nullable<short> ord_release { get; set; }
        public string est_job { get; set; }
        public Nullable<short> est_suf { get; set; }
        public string item { get; set; }
        public decimal qty_released { get; set; }
        public Nullable<decimal> qty_complete { get; set; }
        public Nullable<decimal> qty_scrapped { get; set; }
        public string stat { get; set; }
        public Nullable<System.DateTime> lst_trx_date { get; set; }
        public string root_job { get; set; }
        public Nullable<short> root_suf { get; set; }
        public string ref_job { get; set; }
        public short ref_suf { get; set; }
        public int ref_oper { get; set; }
        public Nullable<short> ref_seq { get; set; }
        public Nullable<byte> low_level { get; set; }
        public Nullable<System.DateTime> effect_date { get; set; }
        public string wip_acct { get; set; }
        public Nullable<decimal> wip_total { get; set; }
        public Nullable<decimal> wip_complete { get; set; }
        public Nullable<decimal> wip_special { get; set; }
        public string revision { get; set; }
        public Nullable<byte> picked { get; set; }
        public string whse { get; set; }
        public string jcb_acct { get; set; }
        public string ps_num { get; set; }
        public string wip_lbr_acct { get; set; }
        public string wip_fovhd_acct { get; set; }
        public string wip_vovhd_acct { get; set; }
        public string wip_out_acct { get; set; }
        public Nullable<decimal> wip_matl_total { get; set; }
        public Nullable<decimal> wip_lbr_total { get; set; }
        public Nullable<decimal> wip_fovhd_total { get; set; }
        public Nullable<decimal> wip_vovhd_total { get; set; }
        public Nullable<decimal> wip_out_total { get; set; }
        public Nullable<decimal> wip_matl_comp { get; set; }
        public Nullable<decimal> wip_lbr_comp { get; set; }
        public Nullable<decimal> wip_fovhd_comp { get; set; }
        public Nullable<decimal> wip_vovhd_comp { get; set; }
        public Nullable<decimal> wip_out_comp { get; set; }
        public Nullable<System.DateTime> rollup_date { get; set; }
        public string wip_acct_unit1 { get; set; }
        public string wip_acct_unit2 { get; set; }
        public string wip_acct_unit3 { get; set; }
        public string wip_acct_unit4 { get; set; }
        public string jcb_acct_unit1 { get; set; }
        public string jcb_acct_unit2 { get; set; }
        public string jcb_acct_unit3 { get; set; }
        public string jcb_acct_unit4 { get; set; }
        public string wip_lbr_acct_unit1 { get; set; }
        public string wip_lbr_acct_unit2 { get; set; }
        public string wip_lbr_acct_unit3 { get; set; }
        public string wip_lbr_acct_unit4 { get; set; }
        public string wip_fovhd_acct_unit1 { get; set; }
        public string wip_fovhd_acct_unit2 { get; set; }
        public string wip_fovhd_acct_unit3 { get; set; }
        public string wip_fovhd_acct_unit4 { get; set; }
        public string wip_vovhd_acct_unit1 { get; set; }
        public string wip_vovhd_acct_unit2 { get; set; }
        public string wip_vovhd_acct_unit3 { get; set; }
        public string wip_vovhd_acct_unit4 { get; set; }
        public string wip_out_acct_unit1 { get; set; }
        public string wip_out_acct_unit2 { get; set; }
        public string wip_out_acct_unit3 { get; set; }
        public string wip_out_acct_unit4 { get; set; }
        public string prod_mix { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string description { get; set; }
        public string config_id { get; set; }
        public Nullable<byte> co_product_mix { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public byte scheduled { get; set; }
        public string rcpt_rqmt { get; set; }
        public string export_type { get; set; }
        public byte contains_tax_free_matl { get; set; }
        public Nullable<System.DateTime> midnight_of_job_sch_end_date { get; set; }
        public Nullable<System.DateTime> midnight_of_job_sch_compdate { get; set; }
        public byte rework { get; set; }
        public byte unlinked_xref { get; set; }
        public string prospect_id { get; set; }
        public byte is_external { get; set; }
        public byte preassign_lots { get; set; }
        public byte preassign_serials { get; set; }
        public string uf_pref_type { get; set; }
    }
}
