//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardDataGatherer
{
    using System;
    using System.Collections.Generic;
    
    public partial class lc_ea_item_whse_loc_facts
    {
        public string Site { get; set; }
        public string Warehouse { get; set; }
        public string Whse_Code_Type { get; set; }
        public string Item_Nbr { get; set; }
        public string Location { get; set; }
        public System.DateTime Record_Date { get; set; }
        public string Record_Type { get; set; }
        public string Perm_Loc { get; set; }
        public string Loc_Type { get; set; }
        public string Loc_Desc { get; set; }
        public string Work_Center { get; set; }
        public string Non_Nettable { get; set; }
        public string Inv_Acct_Unit1 { get; set; }
        public string Inv_Acct_Unit2 { get; set; }
        public string Inv_Acct_Unit3 { get; set; }
        public string Inv_Acct_Unit4 { get; set; }
        public string Lbr_Acct_Unit1 { get; set; }
        public string Lbr_Acct_Unit2 { get; set; }
        public string Lbr_Acct_Unit3 { get; set; }
        public string Lbr_Acct_Unit4 { get; set; }
        public string Fix_OH_Acct_Unit1 { get; set; }
        public string Fix_OH_Acct_Unit2 { get; set; }
        public string Fix_OH_Acct_Unit3 { get; set; }
        public string Fix_OH_Acct_Unit4 { get; set; }
        public string Var_OH_Acct_Unit1 { get; set; }
        public string Var_OH_Acct_Unit2 { get; set; }
        public string Var_OH_Acct_Unit3 { get; set; }
        public string Var_OH_Acct_Unit4 { get; set; }
        public string Outside_Acct_Unit1 { get; set; }
        public string Outside_Acct_Unit2 { get; set; }
        public string Outside_Acct_Unit3 { get; set; }
        public string Outside_Acct_Unit4 { get; set; }
        public string Inv_Acct { get; set; }
        public string Lbr_Acct { get; set; }
        public string Fix_OH_Acct { get; set; }
        public string Var_OH_Acct { get; set; }
        public string Outside_Acct { get; set; }
        public Nullable<short> Rank { get; set; }
        public string Record_Date_Fiscal_Year { get; set; }
        public string Record_Date_Quarter { get; set; }
        public string Record_Date_Period { get; set; }
        public Nullable<decimal> Loc_Unit_Cost { get; set; }
        public Nullable<decimal> Loc_Matl_Cost { get; set; }
        public Nullable<decimal> Loc_Lbr_Cost { get; set; }
        public Nullable<decimal> Loc_Fix_OH_Cost { get; set; }
        public Nullable<decimal> Loc_Var_OH_Cost { get; set; }
        public Nullable<decimal> Loc_Outside_Cost { get; set; }
        public Nullable<decimal> Loc_Qty_On_Hand { get; set; }
        public Nullable<decimal> Loc_Qty_Reserved { get; set; }
        public Nullable<decimal> Transfer_In_YTD { get; set; }
        public Nullable<decimal> Transfer_Out_YTD { get; set; }
        public Nullable<decimal> Whse_Last_Cnt_Qty_On_Hand { get; set; }
        public Nullable<decimal> Whse_Non_Nettable { get; set; }
        public Nullable<decimal> Whse_On_PO { get; set; }
        public Nullable<decimal> Whse_Qty_Alloc_CO { get; set; }
        public Nullable<decimal> Whse_Qty_Alloc_Transfer_Out { get; set; }
        public Nullable<decimal> Whse_Qty_WIP { get; set; }
        public Nullable<decimal> Whse_Qty_On_Hand { get; set; }
        public Nullable<decimal> Whse_Qty_On_Transfer_In { get; set; }
        public Nullable<decimal> Whse_Qty_Purch_YTD { get; set; }
        public Nullable<decimal> Whse_Qty_Reserved { get; set; }
        public Nullable<decimal> Whse_Qty_Sold_YTD { get; set; }
        public Nullable<decimal> Whse_Safety_Stock { get; set; }
        public Nullable<decimal> Whse_Sales_PTD { get; set; }
        public Nullable<decimal> Whse_Sales_YTD { get; set; }
        public Nullable<decimal> Whse_Unit_Cost { get; set; }
        public Nullable<decimal> Whse_Last_Unit_Cost { get; set; }
        public Nullable<decimal> Whse_Avg_Unit_Cost { get; set; }
        public Nullable<decimal> Whse_ASM_Setup { get; set; }
        public Nullable<decimal> Whse_ASM_Run { get; set; }
        public Nullable<decimal> Whse_ASM_Matl { get; set; }
        public Nullable<decimal> Whse_ASM_Tool { get; set; }
        public Nullable<decimal> Whse_ASM_Fixture { get; set; }
        public Nullable<decimal> Whse_ASM_Other { get; set; }
        public Nullable<decimal> Whse_ASM_Fix_OH { get; set; }
        public Nullable<decimal> Whse_ASM_Var_OH { get; set; }
        public Nullable<decimal> Whse_ASM_Outside { get; set; }
        public Nullable<decimal> Whse_Comp_Setup { get; set; }
        public Nullable<decimal> Whse_Comp_Run { get; set; }
        public Nullable<decimal> Whse_Comp_Matl { get; set; }
        public Nullable<decimal> Whse_Comp_Tool { get; set; }
        public Nullable<decimal> Whse_Comp_Fixture { get; set; }
        public Nullable<decimal> Whse_Comp_Other { get; set; }
        public Nullable<decimal> Whse_Comp_Fix_OH { get; set; }
        public Nullable<decimal> Whse_Comp_Var_OH { get; set; }
        public Nullable<decimal> Whse_Comp_Outside { get; set; }
        public Nullable<decimal> Whse_Sub_Matl { get; set; }
        public Nullable<decimal> Whse_Curr_Unit_Cost { get; set; }
        public Nullable<decimal> Whse_Unit_Mat_Cost { get; set; }
        public Nullable<decimal> Whse_Unit_Duty_Cost { get; set; }
        public Nullable<decimal> Whse_Unit_Freight_Cost { get; set; }
        public Nullable<decimal> Whse_Unit_Broker_Cost { get; set; }
        public Nullable<decimal> Whse_Unit_Insurance_Cost { get; set; }
        public Nullable<decimal> Whse_Unit_Loc_Frt_Cost { get; set; }
        public Nullable<decimal> Whse_Curr_Mat_Cost { get; set; }
        public Nullable<decimal> Whse_Curr_Duty_Cost { get; set; }
        public Nullable<decimal> Whse_Curr_Freight_Cost { get; set; }
        public Nullable<decimal> Whse_Curr_Broker_Cost { get; set; }
        public Nullable<decimal> Whse_Curr_Insurance_Cost { get; set; }
        public Nullable<decimal> Whse_Curr_Loc_Frt_Cost { get; set; }
        public Nullable<decimal> Whse_Matl_Cost { get; set; }
        public Nullable<decimal> Whse_Lbr_Cost { get; set; }
        public Nullable<decimal> Whse_Fix_OH_Cost { get; set; }
        public Nullable<decimal> Whse_Var_OH_Cost { get; set; }
        public Nullable<decimal> Whse_Outside_Cost { get; set; }
        public Nullable<decimal> Whse_Curr_Matl_Cost { get; set; }
        public Nullable<decimal> Whse_Curr_Lbr_Cost { get; set; }
        public Nullable<decimal> Whse_Curr_Fix_OH_Cost { get; set; }
        public Nullable<decimal> Whse_Curr_Var_OH_Cost { get; set; }
        public Nullable<decimal> Whse_Curr_Outside_Cost { get; set; }
        public Nullable<decimal> Whse_Avg_Matl_Cost { get; set; }
        public Nullable<decimal> Whse_Avg_Lbr_Cost { get; set; }
        public Nullable<decimal> Whse_Avg_Fix_OH_Cost { get; set; }
        public Nullable<decimal> Whse_Avg_Var_OH_Cost { get; set; }
        public Nullable<decimal> Whse_Avg_Outside_Cost { get; set; }
        public Nullable<decimal> Whse_Inv_Value { get; set; }
        public Nullable<decimal> Loc_Inv_Value { get; set; }
        public Nullable<byte> Deleted { get; set; }
        public Nullable<System.DateTime> ObsoleteDate { get; set; }
        public byte InWorkflow { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Sched_Type { get; set; }
    }
}
