//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardDataGatherer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineHourMetric
    {
        public long ID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string WorkCenter { get; set; }
        public Nullable<decimal> MachineHours { get; set; }
        public Nullable<decimal> FixedOverhead { get; set; }
        public Nullable<decimal> VariableOverhead { get; set; }
    }
}
