using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DashboardDataGatherer.Models
{
    public class Item
    {
        public string item { get; set; }
        public string description { get; set; }
        public Nullable<decimal> qty_used_ytd { get; set; }
        public Nullable<decimal> qty_mfg_ytd { get; set; }
    }

    public partial class item
    {
        public string item1 { get; set; }
        public string description { get; set; }
        public Nullable<decimal> qty_allocjob { get; set; }
        public string u_m { get; set; }
        public short lead_time { get; set; }
        public Nullable<decimal> lot_size { get; set; }
        public Nullable<decimal> qty_used_ytd { get; set; }
        public Nullable<decimal> qty_mfg_ytd { get; set; }
        public string abc_code { get; set; }
        public string drawing_nbr { get; set; }
        public string product_code { get; set; }
        public string p_m_t_code { get; set; }
        public string cost_method { get; set; }
        public Nullable<decimal> lst_lot_size { get; set; }
        public Nullable<decimal> unit_cost { get; set; }
        public Nullable<decimal> lst_u_cost { get; set; }
        public Nullable<decimal> avg_u_cost { get; set; }
        public string job { get; set; }
        public Nullable<short> suffix { get; set; }
        public Nullable<byte> stocked { get; set; }
        public string matl_type { get; set; }
        public string family_code { get; set; }
        public Nullable<byte> low_level { get; set; }
        public Nullable<System.DateTime> last_inv { get; set; }
        public Nullable<short> days_supply { get; set; }
        public Nullable<decimal> order_min { get; set; }
        public Nullable<decimal> order_mult { get; set; }
        public string plan_code { get; set; }
        public Nullable<byte> mps_flag { get; set; }
        public Nullable<byte> accept_req { get; set; }
        public Nullable<System.DateTime> change_date { get; set; }
        public string revision { get; set; }
        public Nullable<byte> phantom_flag { get; set; }
        public Nullable<byte> plan_flag { get; set; }
        public short paper_time { get; set; }
        public short dock_time { get; set; }
        public Nullable<decimal> asm_setup { get; set; }
        public Nullable<decimal> asm_run { get; set; }
        public Nullable<decimal> asm_matl { get; set; }
        public Nullable<decimal> asm_tool { get; set; }
        public Nullable<decimal> asm_fixture { get; set; }
        public Nullable<decimal> asm_other { get; set; }
        public Nullable<decimal> asm_fixed { get; set; }
        public Nullable<decimal> asm_var { get; set; }
        public Nullable<decimal> asm_outside { get; set; }
        public Nullable<decimal> comp_setup { get; set; }
        public Nullable<decimal> comp_run { get; set; }
        public Nullable<decimal> comp_matl { get; set; }
        public Nullable<decimal> comp_tool { get; set; }
        public Nullable<decimal> comp_fixture { get; set; }
        public Nullable<decimal> comp_other { get; set; }
        public Nullable<decimal> comp_fixed { get; set; }
        public Nullable<decimal> comp_var { get; set; }
        public Nullable<decimal> comp_outside { get; set; }
        public Nullable<decimal> sub_matl { get; set; }
        public Nullable<decimal> shrink_fact { get; set; }
        public string alt_item { get; set; }
        public Nullable<decimal> unit_weight { get; set; }
        public string weight_units { get; set; }
        public string charfld4 { get; set; }
        public Nullable<decimal> cur_u_cost { get; set; }
        public string feat_type { get; set; }
        public Nullable<decimal> var_lead { get; set; }
        public string feat_str { get; set; }
        public Nullable<short> next_config { get; set; }
        public string feat_templ { get; set; }
        public Nullable<byte> backflush { get; set; }
        public string charfld1 { get; set; }
        public string charfld2 { get; set; }
        public string charfld3 { get; set; }
        public Nullable<decimal> decifld1 { get; set; }
        public Nullable<decimal> decifld2 { get; set; }
        public Nullable<decimal> decifld3 { get; set; }
        public Nullable<byte> logifld { get; set; }
        public Nullable<System.DateTime> datefld { get; set; }
        public Nullable<byte> track_ecn { get; set; }
        public Nullable<decimal> u_ws_price { get; set; }
        public string comm_code { get; set; }
        public string origin { get; set; }
        public Nullable<decimal> unit_mat_cost { get; set; }
        public Nullable<decimal> unit_duty_cost { get; set; }
        public Nullable<decimal> unit_freight_cost { get; set; }
        public Nullable<decimal> unit_brokerage_cost { get; set; }
        public Nullable<decimal> cur_mat_cost { get; set; }
        public Nullable<decimal> cur_duty_cost { get; set; }
        public Nullable<decimal> cur_freight_cost { get; set; }
        public Nullable<decimal> cur_brokerage_cost { get; set; }
        public string tax_code1 { get; set; }
        public string tax_code2 { get; set; }
        public string bflush_loc { get; set; }
        public Nullable<byte> reservable { get; set; }
        public Nullable<short> shelf_life { get; set; }
        public string lot_prefix { get; set; }
        public string serial_prefix { get; set; }
        public Nullable<byte> serial_length { get; set; }
        public string issue_by { get; set; }
        public Nullable<byte> serial_tracked { get; set; }
        public Nullable<byte> lot_tracked { get; set; }
        public string cost_type { get; set; }
        public Nullable<decimal> matl_cost { get; set; }
        public Nullable<decimal> lbr_cost { get; set; }
        public Nullable<decimal> fovhd_cost { get; set; }
        public Nullable<decimal> vovhd_cost { get; set; }
        public Nullable<decimal> out_cost { get; set; }
        public Nullable<decimal> cur_matl_cost { get; set; }
        public Nullable<decimal> cur_lbr_cost { get; set; }
        public Nullable<decimal> cur_fovhd_cost { get; set; }
        public Nullable<decimal> cur_vovhd_cost { get; set; }
        public Nullable<decimal> cur_out_cost { get; set; }
        public Nullable<decimal> avg_matl_cost { get; set; }
        public Nullable<decimal> avg_lbr_cost { get; set; }
        public Nullable<decimal> avg_fovhd_cost { get; set; }
        public Nullable<decimal> avg_vovhd_cost { get; set; }
        public Nullable<decimal> avg_out_cost { get; set; }
        public string prod_type { get; set; }
        public Nullable<decimal> rate_per_day { get; set; }
        public Nullable<short> mps_plan_fence { get; set; }
        public Nullable<byte> pass_req { get; set; }
        public Nullable<byte> lot_gen_exp { get; set; }
        public string supply_site { get; set; }
        public string prod_mix { get; set; }
        public string stat { get; set; }
        public string status_chg_user_code { get; set; }
        public Nullable<System.DateTime> chg_date { get; set; }
        public string reason_code { get; set; }
        public string supply_whse { get; set; }
        public Nullable<short> due_period { get; set; }
        public Nullable<decimal> order_max { get; set; }
        public Nullable<byte> mrp_part { get; set; }
        public Nullable<byte> infinite_part { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public Nullable<decimal> supply_tolerance_hrs { get; set; }
        public short exp_lead_time { get; set; }
        public Nullable<decimal> var_exp_lead { get; set; }
        public string buyer { get; set; }
        public byte order_configurable { get; set; }
        public byte job_configurable { get; set; }
        public string cfg_model { get; set; }
        public string co_post_config { get; set; }
        public string job_post_config { get; set; }
        public string auto_job { get; set; }
        public string auto_post { get; set; }
        public string setupgroup { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public Nullable<byte> mfg_supply_switching_active { get; set; }
        public Nullable<short> time_fence_rule { get; set; }
        public Nullable<double> time_fence_value { get; set; }
        public Nullable<System.DateTime> earliest_planned_po_receipt { get; set; }
        public Nullable<byte> use_reorder_point { get; set; }
        public Nullable<decimal> reorder_point { get; set; }
        public Nullable<decimal> fixed_order_qty { get; set; }
        public Nullable<decimal> unit_insurance_cost { get; set; }
        public Nullable<decimal> unit_loc_frt_cost { get; set; }
        public Nullable<decimal> cur_insurance_cost { get; set; }
        public Nullable<decimal> cur_loc_frt_cost { get; set; }
        public byte tax_free_matl { get; set; }
        public Nullable<short> tax_free_days { get; set; }
        public decimal safety_stock_percent { get; set; }
        public string tariff_classification { get; set; }
        public Nullable<System.DateTime> lowdate { get; set; }
        public string rcpt_rqmt { get; set; }
        public byte active_for_data_integration { get; set; }
        public Nullable<decimal> rcvd_over_po_qty_tolerance { get; set; }
        public Nullable<decimal> rcvd_under_po_qty_tolerance { get; set; }
        public Nullable<byte> include_in_net_change_planning { get; set; }
        public byte kit { get; set; }
        public byte print_kit_components { get; set; }
        public Nullable<short> safety_stock_rule { get; set; }
        public byte show_in_drop_down_list { get; set; }
        public byte controlled_by_external_ics { get; set; }
        public Nullable<decimal> inventory_ucl_tolerance { get; set; }
        public Nullable<decimal> inventory_lcl_tolerance { get; set; }
        public string separation_attribute { get; set; }
        public Nullable<double> batch_release_attribute1 { get; set; }
        public Nullable<double> batch_release_attribute2 { get; set; }
        public Nullable<double> batch_release_attribute3 { get; set; }
        public byte[] picture { get; set; }
        public byte active_for_customer_portal { get; set; }
        public byte featured { get; set; }
        public byte top_seller { get; set; }
        public string overview { get; set; }
        public byte preassign_lots { get; set; }
        public byte preassign_serials { get; set; }
        public string attr_group { get; set; }
        public string dimension_group { get; set; }
        public string lot_attr_group { get; set; }
        public byte track_pieces { get; set; }
        public Nullable<System.DateTime> bom_last_import_date { get; set; }
        public byte save_current_rev_upon_bom_import { get; set; }
        public string uf_pref_type { get; set; }
        public string nafta_pref_crit { get; set; }
        public byte subject_to_nafta_rvc { get; set; }
        public byte producer { get; set; }
        public string nafta_country_of_origin { get; set; }
        public byte must_use_future_rcpts_before_pln { get; set; }
    }
}
