//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardDataGatherer.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueryDefs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryDefs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DashboardDataGatherer.Models.QueryDefs", typeof(QueryDefs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM MachineHourMetrics.
        /// </summary>
        internal static string DeleteAllMachineHourMetrics {
            get {
                return ResourceManager.GetString("DeleteAllMachineHourMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM WorkOrderMetrics
        ///WHERE MetricType = &apos;~p0&apos; AND DateCreated = &apos;~p1&apos;.
        /// </summary>
        internal static string DeleteWOMetricByTypeAndDate {
            get {
                return ResourceManager.GetString("DeleteWOMetricByTypeAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT lc_ea_item_whse_loc_facts.Warehouse
        ///      ,lc_ea_item_whse_loc_facts.Item_Nbr
        ///      ,lc_ea_item_whse_loc_facts.Record_Date
        ///      ,lc_ea_item_whse_loc_facts.Whse_Qty_On_Hand
        ///      ,lc_ea_item_whse_loc_facts.Whse_Inv_Value
        ///      ,lc_ea_items.Purch_Manuf
        ///FROM lc_ea_item_whse_loc_facts INNER JOIN lc_ea_items
        ///	ON lc_ea_item_whse_loc_facts.Item_Nbr = lc_ea_items.Item_Nbr
        ///WHERE Record_Date &gt;= &apos;~p0&apos; AND Record_Date &lt;= &apos;~p1&apos; AND Record_Type = &apos;Whse&apos; AND Whse_Qty_On_Hand &gt; 0.
        /// </summary>
        internal static string SelectFactTrakItemCostsByDate {
            get {
                return ResourceManager.GetString("SelectFactTrakItemCostsByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM item
        ///WHERE item in (~p0).
        /// </summary>
        internal static string SelectItemByItemList {
            get {
                return ResourceManager.GetString("SelectItemByItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT item
        ///      ,effect_date
        ///      ,curr_code
        ///      ,unit_price1
        ///      ,unit_price2
        ///      ,unit_price3
        ///      ,unit_price4
        ///      ,unit_price5
        ///      ,unit_price6
        ///      ,reprice
        ///      ,brk_qty##1 AS brk_qty__1
        ///      ,brk_qty##2 AS brk_qty__2
        ///      ,brk_qty##3 AS brk_qty__3
        ///      ,brk_qty##4 AS brk_qty__4
        ///      ,brk_qty##5 AS brk_qty__5
        ///      ,brk_price##1 AS brk_price__1
        ///      ,brk_price##2 AS brk_price__2
        ///      ,brk_price##3 AS brk_price__3
        ///      ,brk_price##4 AS brk_price__4
        ///      ,brk_p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectItemPricesByItemList {
            get {
                return ResourceManager.GetString("SelectItemPricesByItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM itemwhse
        ///WHERE item in (~p0).
        /// </summary>
        internal static string SelectItemWhseByItemList {
            get {
                return ResourceManager.GetString("SelectItemWhseByItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT itemwhse.whse AS Warehouse, itemwhse.item AS Item, item.p_m_t_code AS Source, itemwhse.qty_on_hand AS QtyOnHand, 
        ///	item.unit_cost AS UnitCost, (itemwhse.qty_on_hand * item.unit_cost) AS TotalCost
        ///FROM itemwhse
        ///	INNER JOIN item ON item.item = itemwhse.item
        ///WHERE itemwhse.qty_on_hand &gt; 0.
        /// </summary>
        internal static string SelectItemWhseItemCosts {
            get {
                return ResourceManager.GetString("SelectItemWhseItemCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT itemwhse.whse AS Warehouse, item.p_m_t_code AS Source, SUM(itemwhse.qty_on_hand * item.unit_cost) AS TotalCost
        ///FROM itemwhse
        ///	INNER JOIN item ON item.item = itemwhse.item
        ///WHERE itemwhse.qty_on_hand &gt; 0
        ///GROUP BY itemwhse.whse, item.p_m_t_code.
        /// </summary>
        internal static string SelectItemWhseTypeCosts {
            get {
                return ResourceManager.GetString("SelectItemWhseTypeCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT whse, item, SUM(wip_total - wip_complete) AS WIP_Remaining
        ///FROM job
        ///WHERE (wip_total - wip_complete &lt;&gt; 0)
        ///GROUP BY whse, item.
        /// </summary>
        internal static string SelectItemWIPRemaining {
            get {
                return ResourceManager.GetString("SelectItemWIPRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CAST(trans_date AS date) AS TransactionDate, wc AS WorkCenter, SUM(a_hrs) AS MachineHours, SUM(fixovhd) AS FixedOverhead, SUM(varovhd) AS VariableOverhead
        ///FROM jobtran
        ///WHERE CAST(trans_date AS date) IN (SELECT TOP 365 CAST(trans_date AS date) FROM jobtran WHERE trans_type = &apos;C&apos; AND CAST(trans_date AS date) &lt;= &apos;~p0&apos; GROUP BY CAST(trans_date AS date) ORDER BY CAST(trans_date AS date) DESC) AND trans_type = &apos;C&apos;
        ///GROUP BY CAST(trans_date AS date), wc
        ///ORDER BY TransactionDate ASC.
        /// </summary>
        internal static string SelectNMachineTransactions {
            get {
                return ResourceManager.GetString("SelectNMachineTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT item, MAX(trans_date) AS trans_date
        ///  FROM matltran
        ///  WHERE item IN (~p0) AND (trans_type = &apos;S&apos; OR trans_type = &apos;F&apos;)
        ///  GROUP BY item.
        /// </summary>
        internal static string SelectRecentMatlTranByItemList {
            get {
                return ResourceManager.GetString("SelectRecentMatlTranByItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRANT EXECUTE ON [WTF_App].[dbo].Rpt_InventoryCostSp TO WTFApp.
        /// </summary>
        internal static string StoredProcedurePermissions {
            get {
                return ResourceManager.GetString("StoredProcedurePermissions", resourceCulture);
            }
        }
    }
}
